Issue 9 create authentication logic use jwt
LocalizationEditor/localizationeditor pull request #10
Opened 2020-11-30 19:59 UTC by HaptelmanovArtem

2020-12-01 08:10 UTC, slukashov requested changes
есть предложение сразу попробовать обновится на .net 5.0 и быть в тренде)
может подумаем и нафиг откажемся от встроеной DI, а заюзаем что то другое  к примеру [AutoFac](https://autofac.org/).
модуль авторизацию предлагаю обсудить потому что как мне кажется там есть над чем еще подумать)
да и загляни плиз в сонар что мы там можем сразу пофиксить.

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Auth.Application/Fetchers/Commands/AddUserCommandHandler.cs
> +      return await _repository.AddAsync(new UserAuth(default ,request.Email, request.Password));
давай создавать объекты  и записывать их в бд на разных строках

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Localization/Startup.cs
> +      services.AddBase();
предлагаю вот такую регситрацию переписать на автоматическую через рефлексию

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Localization/Startup.cs
> +      services.AddAuthentication("JwtDefaultSchema")
JwtDefaultSchema точно так должно быть ? или можно по нашему назвать?)

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Localization/appsettings.json
> +    "Secret": "123456789KityKello_()_KAk123654987",
интересный секрет а почему он такой?

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base.Auth/Configurations.cs
> +      var section = configuration.GetSection("AuthOptions");
давай работать через объекты и на прямую стараться не получать  секции конфигурации

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/DataLayer/IIdEntity.cs
> +    long Id { get; }
а ты не хочешь уйти от прямого id к Guid?

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/DataLayer/INameEntity.cs
> +  public interface INameEntity
INamedEntity ?

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Utils/Coder.cs
> +    private const string Key = "9NZXRnJVNLsrVRsiHv13Kxc7j6jmOI8=";
это точно тут не нужно)

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Utils/Coder.cs
> +  public class Coder
а может поищем реализацию уже готового шифратора и не будем изобретать свой велосипед

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Utils/DbCoder.cs
> +  internal class DbCoder : IDbCoder
мне кажется что имя DbCoder не совсем уместно , потому что использовать оно может где угодно и к БД напрямую неотносится

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Migration/Migration.csproj
> +      <PackageReference Include="FluentMigrator.Runner" Version="3.2.9" />
FluentMigrator должно хватать вроде с головой все остальное нам не нужно вроде)

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Migration/Program.cs
> +            .WithGlobalConnectionString("Server=(localdb)\\MSSQLLocalDB;Database=LocalizationEditor;Trusted_Connection=True;")
строка подключения

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Migration/Program.cs
> +    private static void UpdateDatabase(IServiceProvider serviceProvider)
не нужен отдельный метод

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Migration/Migrations/CreateAuthUserTable.cs
> +  [Migration(202011260, "a.haptelmanov issue-9")]
давай напишем свой аттрибут  и будем дату туда передовать почеловечески

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Utils/Json/SensitivePropertyAttribute.cs
> +  public class SensitivePropertyAttribute : Attribute
эта штука используется для клиента?

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/DataLayer/Infrastructure/BaseContext.cs
> +        .UseSqlServer(_connectionString);
нам для авторизации прям 100% нужна база?
если да то давай подумаем над тем как потом нам обновляться.
решение мы же стараемся сделать не зависимым. то есть это окей что мы заюзаем EF, использовать SQL server не уверен.
если нам нужно испоьлзовтаь какую то локальную бд для каких либо целей там сохранение истории и тд  можно рассмотреть вариант с [SQLLite](https://www.sqlite.org/index.html).

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base.Auth/Configurations.cs
> +      var section = configuration.GetSection("AuthOptions");
темболее что я видел  ниже options создаются

2020-12-01 08:10 UTC, slukashov commented on LocalizationEditor/Auth.Persistence/Context/AuthContext.cs
> +      : base("Server=(localdb)\\MSSQLLocalDB;Database=LocalizationEditor;Trusted_Connection=True;")
строка подключения  зашитая в коде не круто)

2020-12-03 18:16 UTC, closed without merging

2020-12-03 18:17 UTC, HaptelmanovArtem commented
Решили отложить авторизацию