Issue 4 create dialogue for crud operations with connection strings[WIP]
LocalizationEditor/localizationeditor pull request #13
Opened 2020-12-27 13:44 UTC by HaptelmanovArtem

2020-12-27 18:54 UTC, slukashov requested changes
постарался очень внимательно просмотреть)

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Extensions/AutofacExtensions.cs
> +    public static void AddDependencyInjection(this ContainerBuilder builder, Assembly rootAssembly)
скажи а нам нужно этот класс расширение?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Extensions/IConfigurationModule.cs
> +  public interface IConfigurationModule
не хочешь сразу расширить для HostingVariables

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/LocalizationEditor.ConnectionStrings.csproj
> +        <TargetFramework>netcoreapp3.1</TargetFramework>
почему  решил проект netcoreapp3.1 а не netstandard 2.1?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task SaveConnectionAsync(IConnection connection)
- лучше назвать AddOrUpdate,
- почем мы не возвращаем Task<IConnection>
- а вообще скажи  что мы выигрываем от метода  гибридного , ведь если вызывать отдельно add и update соответственно у нас не будет проверки IsNewEntity

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +          entity.Update(
почему не принимать во внутрь такой же объект и там уже обновлять?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +      var json = await File.ReadAllTextAsync(_pathOptionsProvider.FileName);
почему бы тут не проверять на наличие  файла а не на уровень выше?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/MssqlConnectionResolver.cs
> +      return $"Server={Connection.Server};Database={Connection.DbName};User={Connection.UserName};Password={Connection.Password}";
а ты не рассматривал вариант строки подключения через windows auth ?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionController.cs
> +      return Enum.GetValues(typeof(DbType)).Cast<DbType>()
а вот эту шляпу можно точно вынести в extensions Enum.GetValues(typeof(T)).Cast<T>()

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionController.cs
> +    public async Task<ConnectionViewModel> Update(ConnectionViewModel model)
а httpput id не должен принимать?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionController.cs
> +  public class ConnectionController : ControllerBase
оберни плиз все возвращаемые типы в ActionResult

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Extensions/ServiceCollectionExtensions.cs
> +        .SelectMany(assembly => assembly.GetTypes())
where может стоит перенести в SelectMany?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Configuration.cs
> +    public IConfiguration ConfigurationRoot { get; set; }
нам точно нужен публичный сеттер? может сделать отдельный метод ? куда будер передаваться нужные параметры ?  + как вариант сделать базовый модуль что бы от него все наследовалось

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/ConnectionDto.cs
> +      Id = id;
в каких случаях нам нужно обновлять id?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/ConnectionDto.cs
> +    public DbType DataBaseType { get; private set; }
а строка подключения должна знать к какому типу БД?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task<IReadOnlyCollection<IConnection>> GetConnectionsAsync()
лучше верни IEnumerable<T>

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +        return null;
Enumerable<>.Empty();

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionConfigViewModel.cs
> +  {
а конфиг создан только для DbTYpe?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ViewMapperProfiles/ConnectionViewMapper.cs
> +        .ConstructUsing((source, ctx) => new ConnectionDto(
тебе поидее хватит просто source без контекста

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/ClientApp/src/app/connection/components/dialogs/connection-edit-dialog.component.html
> +     [ngStyle]='{"display":"flex",
а мы это в класс не можем унести?

2020-12-27 18:54 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/ClientApp/src/app/connection/components/view/connection-view.component.html
> +      <table mat-table [dataSource]="connections" class="mat-elevation-z8">
давай таблицу переделаем с использованием аттрибтуов mat-table, mat-header-cell, mat-cell соответственно, так таблица будет responsive

2020-12-27 18:57 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Base/Extensions/AutofacExtensions.cs
> +    public static void AddDependencyInjection(this ContainerBuilder builder, Assembly rootAssembly)
Я думаю да, потому что у него будет одна ответственность расширения для autofac если понадобиться написать еще какие-то расширение то они будут тут

2020-12-27 18:59 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionConfigViewModel.cs
> +  {
Да

2020-12-27 19:03 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/LocalizationEditor.ConnectionStrings.csproj
> +        <TargetFramework>netcoreapp3.1</TargetFramework>
по дефолту наверное так, изменю

2020-12-27 20:37 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Base/Extensions/AutofacExtensions.cs
> +    public static void AddDependencyInjection(this ContainerBuilder builder, Assembly rootAssembly)
Ну смотри из того что я сейчас вижу метод реально состоит из одной строки которую можно поместить в стартапе

2020-12-27 20:40 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionConfigViewModel.cs
> +  {
Ну тогда у меня есть предложение) если так и всегда будет то давай дадим название модели более  четкоет или же будем в конфиге возвращать массив dbtype которые в свою очередь idname

2020-12-28 16:33 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/ConnectionDto.cs
> +    public DbType DataBaseType { get; private set; }
мне кажется да, я точно не знаю, но предполагаю что в разных бд разные строки подключения, возможно я не прав

2020-12-28 16:34 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/MssqlConnectionResolver.cs
> +      return $"Server={Connection.Server};Database={Connection.DbName};User={Connection.UserName};Password={Connection.Password}";
нет, сделал так же как у нас в локализаторе

2020-12-28 16:36 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/ConnectionDto.cs
> +      Id = id;
когда новая запись с фронта приходит Ид 0. Нам нужно получить следующий после максимального и обновить модель

2020-12-28 17:00 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task SaveConnectionAsync(IConnection connection)
почем мы не возвращаем Task, мне нужен void asyn void делать нельзя в итоге таск

2020-12-28 18:29 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Base/Extensions/AutofacExtensions.cs
> +    public static void AddDependencyInjection(this ContainerBuilder builder, Assembly rootAssembly)
обновил

2020-12-28 18:29 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Base/Extensions/IConfigurationModule.cs
> +  public interface IConfigurationModule
добавил класс

2020-12-28 18:30 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task SaveConnectionAsync(IConnection connection)
добавил отдельно адд и апдейт

2020-12-28 18:30 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +          entity.Update(
изменил

2020-12-28 18:30 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +        return null;
изменил

2020-12-28 18:30 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ViewMapperProfiles/ConnectionViewMapper.cs
> +        .ConstructUsing((source, ctx) => new ConnectionDto(
удалил

2020-12-28 18:30 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/ClientApp/src/app/connection/components/dialogs/connection-edit-dialog.component.html
> +     [ngStyle]='{"display":"flex",
унес

2020-12-28 18:31 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/ClientApp/src/app/connection/components/view/connection-view.component.html
> +      <table mat-table [dataSource]="connections" class="mat-elevation-z8">
по идеи она такая и была я просто передавал использовал по другому. изменил

2020-12-28 18:33 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +          entity.Update(
изменил

2020-12-28 18:33 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +      var json = await File.ReadAllTextAsync(_pathOptionsProvider.FileName);
переписал немного эту часть

2020-12-28 18:34 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionController.cs
> +      return Enum.GetValues(typeof(DbType)).Cast<DbType>()
вынес эту шляпу)

2020-12-28 18:34 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/Area/ConnectionStrings/ConnectionController.cs
> +    public async Task<ConnectionViewModel> Update(ConnectionViewModel model)
изменил, теперь принимает

2020-12-28 18:34 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Base/Extensions/ServiceCollectionExtensions.cs
> +        .SelectMany(assembly => assembly.GetTypes())
done

2020-12-28 18:34 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Configuration.cs
> +    public IConfiguration ConfigurationRoot { get; set; }
добавил метод

2020-12-28 18:40 UTC, HaptelmanovArtem reviewed
.

2020-12-29 06:16 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/ConnectionDto.cs
> +      Id = id;
Туттнарврное лучше было бы использовать guid

2020-12-29 06:17 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task SaveConnectionAsync(IConnection connection)
Такта почему не сделать возвращаемый тип в методе что бы он перестал быть void

2020-12-29 12:32 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task SaveConnectionAsync(IConnection connection)
сделаю, как раз на фронт уже возвращать сохраненную модель

2020-12-31 07:30 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Models/ConnectionDto.cs
> +      Id = id;
done

2020-12-31 07:50 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task UpdateConnection(Guid id, IConnection connection)
В апдейте ненужен возвращаемый результат?

2020-12-31 07:50 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +      var existConnections = new List<IConnection>(await GetConnectionsAsync());
Мы будем шифровать строки подключения?

2020-12-31 07:50 UTC, slukashov commented on LocalizationEditor/LocalizationEditor.Web/ClientApp/src/app/connection/components/dialogs/connection-edit-dialog.component.ts
> +        console.log("add close dialog")
Console log нужен?

2020-12-31 08:36 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +    public async Task UpdateConnection(Guid id, IConnection connection)
зачем? я просто верну то что пришло мне во вью

2020-12-31 08:37 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.Web/ClientApp/src/app/connection/components/dialogs/connection-edit-dialog.component.ts
> +        console.log("add close dialog")
думаю нет, это был тест, контекст выполнения менялся и функции из этого компонента не выполнялись

2020-12-31 08:37 UTC, HaptelmanovArtem commented on LocalizationEditor/LocalizationEditor.ConnectionStrings/Services/ConnectionService.cs
> +      var existConnections = new List<IConnection>(await GetConnectionsAsync());
да, нужно прикрутить

2021-01-15 13:41 UTC, slukashov approved these changes

2021-01-20 11:30 UTC, merged